name: Lint project with clj-kondo

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2024.01.01'
    - name: Run clj-kondo
      run: clj-kondo --lint src test
