name: Lint project with clj-kondo

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v4
    - uses: DeLaGuardo/setup-clj-kondo@v1
      with:
        version: '2024.11.14'
    - name: Run clj-kondo
      run: clj-kondo --lint src test
