name: Lint project with clj-kondo

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: DeLaGuardo/setup-clj-kondo@v1
      with:
        version: '2020.04.05'
    - uses: actions/checkout@v2.3.3
    - name: Run clj-kondo on ubuntu
      run: clj-kondo --lint src test
